# Generated by Django 5.0.4 on 2024-04-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_number', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='dc_images/')),
                ('description', models.CharField(max_length=1000)),
                ('event_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('is_GRN', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='invoice_images/')),
                ('description', models.CharField(max_length=1000)),
                ('invoice_date', models.DateField()),
                ('sent_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('is_sent', models.BooleanField(default=False)),
                ('is_amount_received', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('expense', models.IntegerField()),
                ('total_bills', models.IntegerField()),
                ('profit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('po_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('po_amount', models.IntegerField()),
                ('po_remaining_amount', models.IntegerField(blank=True, null=True)),
                ('dc', models.ManyToManyField(blank=True, null=True, to='main.deliverychallan')),
                ('invoices', models.ManyToManyField(blank=True, null=True, to='main.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purchaseorder'),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purchaseorder'),
        ),
    ]
