# Generated by Django 5.0.4 on 2024-04-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('event_date', models.DateField()),
                ('quote_date', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
                ('is_po_approved', models.BooleanField(default=False)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.purchaseorder')),
            ],
        ),
    ]
