# Generated by Django 5.0.4 on 2024-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_purchaseorder_grn_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='grn_amount',
            field=models.IntegerField(default=0),
        ),
    ]
