# Generated by Django 5.0.4 on 2024-04-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quote_participants_alter_purchaseorder_grn_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverychallan',
            old_name='event_date',
            new_name='dc_date',
        ),
        migrations.RenameField(
            model_name='deliverychallan',
            old_name='is_GRN',
            new_name='is_grn',
        ),
    ]
