# Generated by Django 5.0.4 on 2024-04-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_event_date_deliverychallan_dc_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profit',
        ),
    ]
