# Generated by Django 5.0.4 on 2024-06-28 13:13

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_img',
            field=models.ImageField(default=1, upload_to='quote_images/', validators=[main.validators.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
