# Generated by Django 5.0.4 on 2024-06-28 13:23

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_quote_quote_img_alter_invoice_sent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='image',
            field=models.ImageField(upload_to='dc_images/', validators=[main.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='image',
            field=models.ImageField(upload_to='invoice_images/', validators=[main.validators.validate_file_extension]),
        ),
    ]
