# Generated by Django 5.0.4 on 2024-07-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_deliverychallan_grn_id_invoice_dc_invoice_grn_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='grn_amount_by_dc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_remaining_amount_by_dc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
