# Generated by Django 5.0.4 on 2024-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_purchaseorder_grn_amount_by_dc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='image',
            field=models.ImageField(upload_to='dc_images/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='image',
            field=models.ImageField(upload_to='invoice_images/'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='dc',
            field=models.ManyToManyField(blank=True, to='main.deliverychallan'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='invoices',
            field=models.ManyToManyField(blank=True, to='main.invoice'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_img',
            field=models.ImageField(upload_to='quote_images/'),
        ),
    ]
